openapi: 3.0.0
info:
  title: REST API for Library system
  description: REST API for Library system
  version: 1.0.0
  contact:
    email: example@gmail.com
    name: REST API example
tags:
  - name: library
    description: everything about books
paths:
  /books:
    get:
      tags:
        - library
      description: Use this API to fetch all books
      responses:
        "200":
          description: all books fetched successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/book"
  /books/{book_id}:
    get:
      tags:
        - library
      description: Use this API to fetch details of a course
      parameters:
        - name: book_id
          required: true
          in: path
          schema:
            type: integer
      responses:
        "200":
          description: course created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/book"

components:
  schemas:
    book:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        id:
          type: integer
    books:
      type: array
      items:
        $ref: "#/components/schemas/book"
